project:
  type: website

website:
  title: "Introduction to Python for Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
        

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



